name: spec-version

on:
  pull_request:

permissions:
  contents: read

jobs:
  spec-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - run: python3 scripts/test-check-spec-versions.py

      - env:
          BASE: origin/${{ github.base_ref }}
        run: python3 scripts/check-spec-versions.py "$BASE"
